# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - 1.1

matrix:
  exclude:
    - os: windows
      language: julia

  include:
    - os: linux

    - os: windows
      language: sh
      before_install:
        - choco install julia
        - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

before_script:
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/wookay/DataLogger.jl.git"'
  - julia --color=yes -e 'using Pkg; pkg"dev Morton"'
  - julia --color=yes -e 'using Pkg; pkg"precompile"'
  - JULIA_DEBUG="all" julia --color=yes -e '@debug 1+2+3'
  -                   julia --color=yes -e '@debug 5+6+7'

script:
  - if [[ "$TRAVIS_OS_NAME" != windows ]] ; then JIVE_PROCS=auto julia --color=yes -e 'using Pkg; Pkg.test()' ; fi
  - if [[ "$TRAVIS_OS_NAME" == windows ]] ; then JIVE_PROCS=auto julia --color=yes -e 'using Pkg; pkg"dev ."; pkg"test TestJulia07"' ; fi
