# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - 1.0
  - nightly

matrix:
  exclude:
    - os: osx
      julia: nightly

    - os: windows
      julia: nightly
      language: julia

  include:
    - os: osx

    - os: windows
      language: sh
      before_install:
        - choco install julia
        - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
      script:
        - julia --color=yes -e 'using Pkg; pkg"dev ."; pkg"test TestJulia07"'

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

before_script:
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/wookay/Jive.jl.git https://github.com/wookay/DataLogger.jl.git"'
  - julia --color=yes -e 'using Pkg; pkg"dev Flux"'
  - julia --color=yes -e 'using Pkg; pkg"precompile"'
