# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
#  - osx
#  - windows

julia:
  - 1.2
  - 1.3

addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy

before_script:
  - julia --color=yes --project -e 'using Pkg; pkg"add PyCall"; pkg"build PyCall"'
  - julia --color=yes --project -e 'using Pkg; pkg"dev Jive"' # Jive v0.1.14
  - julia --color=yes --project -e 'using Pkg; pkg"add Flux#zygote"'
  - julia --color=yes --project -e 'using Pkg; pkg"dev Metalhead"'
  - julia --color=yes --project -e 'using Pkg; pkg"dev Images"'
  - julia --color=yes --project -e 'using Pkg; pkg"add https://github.com/wookay/DataLogger.jl.git"'
  - julia --color=yes --project -e 'using Pkg; pkg"add https://github.com/gasagna/Flows.jl.git"'
  - julia --color=yes --project -e 'using Pkg; pkg"instantiate"; pkg"precompile"'
  - JULIA_DEBUG="all" julia --color=yes -e '@debug 1+2+3'
  -                   julia --color=yes -e '@debug 5+6+7'

script:
  - JIVE_PROCS=auto julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
