# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
#  - osx
#  - windows

julia:
  - 1.1
  - 1.3
  - nightly

cache:
  directories:
  - $HOME/.julia/artifacts

before_script:
  - julia --color=yes -e 'using Pkg; pkg"registry add https://github.com/JuliaRegistries/General.git"'
  - julia --color=yes --project=. -e 'using Pkg; pkg"registry add https://github.com/wookay/Registro.git"'
  - julia --color=yes --project=. -e 'using Pkg; pkg"up"'
  - julia --color=yes --project=. -e 'using Pkg; pkg"instantiate"; pkg"precompile"'
  - JULIA_DEBUG="all" julia --color=yes -e '@debug 1+2+3'
  -                   julia --color=yes -e '@debug 5+6+7'

script:
  - JIVE_PROCS=auto julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
