## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
addons:
  apt:
    packages:
      - python-numpy
      - python3-numpy
notifications:
  email: false
git:
  depth: 99999999

before_script:
  - julia -e 'using Pkg; pkg"add https://github.com/wookay/DataLogger.jl.git https://github.com/wookay/Jive.jl.git"'
  - julia -e 'using Pkg; pkg"precompile"'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("TestJulia07")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TestJulia07")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
