name: CI

on:
  push:
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.9.3]
        julia-arch: [x64]
        os: [ubuntu-latest]
        include:
          - julia-version: nightly
            os: ubuntu-latest
          - julia-version: 1.8.5
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: runtests
        run: |
             julia --project=. -e 'using Pkg; Pkg.test()'
